### ISSUE TITLE
Dungeon-Starter unter macOS

### ISSUE THREAD

**Issue by cagix** [PM-Dungeon/dungeon-starter#67]
Unter macOS (Intel, 12.3.1 Monterey) kann man das frisch ausgecheckte Desktop-Projekt starten (`./gradlew run`) und ein Dungeon erscheint. Wenn man dem Quickstart-Guide folgt und alles (bis vor die letzte Section bzgl. Audio), dann erscheint nur noch ein schwarzes Fenster. Hab ich was falsch gemacht?

**Comment by cagix** [comment]
Genauer: Ein initiales `./gradlew run` direkt nach dem Auschecken funktioniert noch. Das Fenster erscheint, und manchmal braucht es eine lange Weile, bevor etwas angezeigt wird. (Sollte das ggf. im Guide erklärt werden?!)

Dann habe ich entsprechend https://github.com/PM-Dungeon/desktop/blob/master/documentation/quickstart_de.md#eigener-held den eigenen Helden implementiert, bis zum Abschnitt "Intermezzo: Der Assets-Ordner". Danach bekomme ich eine Fehlermeldung:

```
code % ./gradlew run

> Task :run
AL lib: (EE) ca_open_playback: AudioUnitInitialize failed
Exception in thread "LWJGL Application" java.lang.NullPointerException: Cannot invoke "graphic.Painter.draw(String, tools.Point, com.badlogic.gdx.graphics.g2d.SpriteBatch)" because the return value of "interfaces.IEntity.getPainter()" is null
        at interfaces.IEntity.draw(IEntity.java:32)
        at desktop.MyHero.update(MyHero.java:30)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at controller.EntityController.update(EntityController.java:12)
        at controller.MainController.render(MainController.java:70)
        at com.badlogic.gdx.Game.render(Game.java:46)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:232)
        at com.badlogic.gdx.backends.lwjgl.DungeonApplication.mainLoop(DungeonApplication.java:34)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 4s
3 actionable tasks: 1 executed, 2 up-to-date
```

Das Fenster erscheint kurz, ist schwarz und dann stürzt der Spass ab.

Mac-Geschichte oder Anleitung kaputt?

**Comment by cagix** [comment]
Und was ist mit den `Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.`????

**Comment by cagix** [comment]
tja, in der Anleitung fehlt, dass man in `MyHero#getPainter` ein `return painter;` einbauen sollte :/

**Comment by cagix** [comment]
so, nun bekomme ich den fehler

```
code % ./gradlew run

> Task :run
AL lib: (EE) ca_open_playback: AudioUnitInitialize failed
Exception in thread "LWJGL Application" java.lang.NullPointerException
        at java.base/java.io.File.<init>(File.java:278)
        at com.badlogic.gdx.files.FileHandle.<init>(FileHandle.java:81)
        at com.badlogic.gdx.backends.lwjgl.LwjglFileHandle.<init>(LwjglFileHandle.java:29)
        at com.badlogic.gdx.backends.lwjgl.LwjglFiles.internal(LwjglFiles.java:42)
        at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:110)
        at textures.TextureMap.getTexture(TextureMap.java:19)
        at graphic.Painter.draw(Painter.java:51)
        at interfaces.IEntity.draw(IEntity.java:32)
        at desktop.MyHero.update(MyHero.java:29)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at controller.EntityController.update(EntityController.java:12)
        at controller.MainController.render(MainController.java:70)
        at com.badlogic.gdx.Game.render(Game.java:46)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:232)
        at com.badlogic.gdx.backends.lwjgl.DungeonApplication.mainLoop(DungeonApplication.java:34)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 22s
3 actionable tasks: 2 executed, 1 up-to-date
```

**Comment by cagix** [comment]
@AMatutat Wieso muss ich eigentlich eine Batch und einen Painter mitführen im Helden? Ich kriege das einmal übergeben und muss die dann wieder rausrücken in extra Gettern. Aber wo brauche ich die wirklich? Ist das nicht etwas, was in der übergeordneten ControllerIrgendwas gehandelt werden sollte?

**Comment by Tobias321** [comment]
`config."disableAudio"();` könnte das playback-Problem beheben. Ich meine, das hatten wir schon mal.

**Comment by cagix** [comment]
> `config."disableAudio"();` könnte das playback-Problem beheben. Ich meine, das hatten wir schon mal.

vorschlag: das kommt in die default-konfig, und im quickstart kommt unter "audio" der hinweis, das im gradle.build wieder rauszunehmen...

aber ich glaube nicht, dass das für die exception ursächlich ist. vermutlich fehlt noch was im guide.

**Comment by AMatutat** [comment]
> @AMatutat Wieso muss ich eigentlich eine Batch und einen Painter mitführen im Helden? Ich kriege das einmal übergeben und muss die dann wieder rausrücken in extra Gettern. Aber wo brauche ich die wirklich? Ist das nicht etwas, was in der übergeordneten ControllerIrgendwas gehandelt werden sollte?

Darüber haben wir schon lang und ausführlich diskutiert..... Wir sollten sowas aufschreiben.
tldr: Die Entitäten sind so eigenständiger und es lassen sich für bestimme Anlässe (die muss sich halt wer überlegen) spezifischen Painter und/oder Batches benutzen.

**Comment by cagix** [comment]
> > @AMatutat Wieso muss ich eigentlich eine Batch und einen Painter mitführen im Helden? Ich kriege das einmal übergeben und muss die dann wieder rausrücken in extra Gettern. Aber wo brauche ich die wirklich? Ist das nicht etwas, was in der übergeordneten ControllerIrgendwas gehandelt werden sollte?
> 
> 
> 
> Darüber haben wir schon lang und ausführlich diskutiert..... Wir sollten sowas aufschreiben.
> 
> tldr: Die Entitäten sind so eigenständiger und es lassen sich für bestimme Anlässe (die muss sich halt wer überlegen) spezifischen Painter und/oder Batches benutzen. 
> 
> 

hihi, ich weiß. aber ich bin heute mal student im zweiten semester, kann grad so ne ide bedienen und ne klasse schreiben und vererbung einsetzen. für mich ist deine aussage grad absoluter overkill (und unverständlich).


> 
> Zu deinem Error: Kannst du uns irgendwie deinen Code zur Einsicht geben? NullPointer klinkt für mich so, als würdest du auf ein File verweisen, dass es gar nicht gibt, 

kopiere einfach die schnipsel aus dem starterguide zusammen, dann hast du meinen code. ich habe exakt die anleitung nachgebaut und 2x geschaut, ob ich irgendwo irgendwas übersehen habe.

**Comment by Tobias321** [comment]
Bei Windows bekomme ich folgende Meldung:

```
Win10, IntelliJ und Eclipse Run MyGame:

> Task :run
AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80070490
AL lib: (EE) MMDevApiOpenPlayback: Device init failed: 0x80070490
org.lwjgl.LWJGLException: Could not locate OpenAL library.
        at org.lwjgl.openal.AL.create(AL.java:156)
        ...
```

Das Spiel funktioniert aber dennoch...

***

> Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

```
The JavaExec.main property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the mainClass property instead. See https://docs.gradle.org/7.2/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.Ja
vaExec:main for more details.
        at ...
```

Dafür hab ich noch keine Lösung... also, wie man "mainClass" vermeiden könnte...

**Comment by cagix** [comment]
Der Starter funktioniert mittlerweile auf macOS/Intel, der Quickstart-Guide ist gefixt. Für die Warning bzgl. Audio gibt es noch #87.

Aus meiner Sicht ist hier nix mehr zu tun, ich mach mal zu.
